name: Build/Release

on: push

jobs:
  release:
    runs-on: ${{matrix.os}}

    strategy:
      matrix:
        os: [windows-latest, macos-latest]
      fail-fast: false
    steps:
      - name: Checking out Git
        uses: actions/checkout@v2

      - name: Setting up Node JS and Yarn
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Installing typescript
        run: yarn global add typescript

      - name: 🔨 Installing dependencies
        run: yarn install

      - name: 🔨 Building app
        run: yarn build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 📤 Publishing ${{matrix.os}} app
        run: yarn upload
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
